services:
  xsshunterexpress-db:
    image: postgres
    container_name: xsshunterexpress-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-db-data:/var/lib/postgresql/data/pgdata
  xsshunterexpress-service:
    build: .
    container_name: xsshunterexpress-service
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - 8080
    volumes:
      - ./payload-fire-images:/app/payload-fire-images
      - ~/.config/gcloud/application_default_credentials.json:/gcloud.json
    depends_on:
      xsshunterexpress-db:
        condition: service_healthy
  xsshunterexpress-trufflehog:
    build:
      dockerfile: Dockerfile.trufflehog
    container_name: xsshunterexpress-trufflehog
    restart: unless-stopped
    expose:
      - 8000
